# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_base_version=1.21.9
minecraft_version=1.21.10
yarn_mappings=1.21.10+build.2
loader_version=0.17.3
# Mod Properties
mod_version=0.13.0-alpha.9
maven_group=io.wispforest
archives_base_name=owo-lib
# Dependencies
fabric_version=0.136.0+1.21.10

# https://maven.shedaniel.me/me/shedaniel/RoughlyEnoughItems-fabric/
rei_version=20.0.811

# https://maven.terraformersmc.com/releases/dev/emi/emi-fabric/
emi_version=1.1.18+1.21.1

# https://search.maven.org/artifact/blue.endless/jankson
jankson_version=1.2.2

# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu_version=15.0.0-beta.3

# https://maven.nucleoid.xyz/xyz/nucleoid/server-translations-api/
stapi_version=2.5.2+1.21.9-pre3
