pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'RelativityMC'
            url = 'https://repo.codemc.io/repository/relativitymc/'
        }
        gradlePluginPortal()
    }
}

//include 'owo-sentinel'