/*
 * This source file was generated by the Gradle 'init' task
 */
package io.wispforest;

import java.lang.instrument.ClassFileTransformer;
import java.lang.instrument.IllegalClassFormatException;
import java.lang.instrument.Instrumentation;
import java.security.ProtectionDomain;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

public class BraidReloadAgent {
    public static void premain(String agentArgs, Instrumentation instrumentation) {
        System.out.println("braid agent init");
        instrumentation.addTransformer(new RedefinitionListener());
    }
}

class RedefinitionListener implements ClassFileTransformer {

    private final Map<String, Integer> classHashes = new HashMap<>();

    @Override
    public byte[] transform(Module module, ClassLoader loader, String className, Class<?> classBeingRedefined, ProtectionDomain protectionDomain, byte[] classfileBuffer) throws IllegalClassFormatException {
        var newHash = Arrays.hashCode(classfileBuffer);

        if (classBeingRedefined != null && this.classHashes.containsKey(className)) {
            var hash = this.classHashes.get(className);
            if (hash != newHash) {
                System.out.println("REDEFINITION: " + className);
            }
        }

        this.classHashes.put(className, newHash);

        return ClassFileTransformer.super.transform(module, loader, className, classBeingRedefined, protectionDomain, classfileBuffer);
    }
}