package io.wispforest.owo.config.base;

import java.util.Arrays;
import java.util.List;

/**
 * Describes an option's location inside a
 * config, generated from its name a potential
 * parents it is nested in
 *
 * @param path The segments of the path making up this key
 */
public record Key(String[] path) {

    public static final Key ROOT = new Key(new String[0]);

    public Key(List<String> path) {
        this(path.toArray(String[]::new));
    }

    public Key(String key) {
        this(key.split("\\."));
    }

    /**
     * @return The immediate parent of this key,
     * or {@link #ROOT} if the parent is the root key
     */
    public Key parent() {
        if (this.path.length <= 1) return ROOT;

        var newPath = new String[this.path.length - 1];
        System.arraycopy(this.path, 0, newPath, 0, this.path.length - 1);
        return new Key(newPath);
    }

    /**
     * Create the key for a child of this key
     *
     * @param childName The name of the child
     */
    public Key child(String childName) {
        var newPath = new String[this.path.length + 1];
        System.arraycopy(this.path, 0, newPath, 0, this.path.length);
        newPath[this.path.length] = childName;
        return new Key(newPath);
    }

    /**
     * @return The segments of this key joined with {@code .}
     */
    public String asString() {
        return String.join(".", this.path);
    }

    /**
     * @return The name of the element this key describes,
     * without any of its parents
     */
    public String name() {
        if (this.path.length < 1) return "";
        return this.path[this.path.length - 1];
    }

    /**
     * @return {@code true} if and only if this
     * key is reference-equal to {@link #ROOT}
     */
    public boolean isRoot() {
        return this == ROOT;
    }

    // Records don't play nicely with arrays, thus need to manually
    // declare all the record autogenerated stuff here

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Key key = (Key) o;
        return Arrays.equals(path, key.path);
    }

    @Override
    public int hashCode() {
        return Arrays.hashCode(path);
    }

    @Override
    public String toString() {
        return "Key{" + "path=" + Arrays.toString(path) + '}';
    }
}
